In [2]:
# numpy 사용하기
import numpy as np

In [4]:
data1 = [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [6]:
data2 = [1,2,3,3.5,4]
data2

[1, 2, 3, 3.5, 4]

In [8]:
# numpy를 이용하여 array 정의하기
# 1. 위에서 만든 python list를 이용
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [9]:
# array의 형태(크기)를 확인할 수 있다.
arr1.shape

(5,)

In [10]:
# 바로 python list를 넣어 줌으로써 만들기
arr2 = np.array([1,2,3,4,5])
arr2

array([1, 2, 3, 4, 5])

In [12]:
arr2.shape

(5,)

In [15]:
# array의 자료형을 확인할 수 있다.
arr2.dtype

dtype('int32')

In [17]:
arr3 = np.array(data2)
arr3

array([1. , 2. , 3. , 3.5, 4. ])

In [19]:
arr3.shape

(5,)

In [21]:
arr3.dtype

dtype('float64')

In [25]:
arr4 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])  # 대괄호 주의
arr4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
arr4.shape

(4, 3)

numpy shape

numpy에서는 해당 array의 크기를 알 수 있다.

shape 을 확인함으로써 몇개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.

위에서 arr1.shape의 결과는 (5,) 으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.

arr4.shape의 결과는 (4,3) 으로써, 2차원의 데이터이며 4 * 3 크기를 갖고 있는 array 이다.

In [29]:
# np.zeros()
# np.zeros() 함수는 인자로 받는 크키만큼, 모든요소가 0인 array를 만든다.

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
#np.ones()
# np.ones() 함수는 인자로 받는 크기만큼, 모든 요소가 1인 array를 만든다.

np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [37]:
np.ones((2,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [43]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
# 기본적으로 numpy에서 연산을 할때는 크기가 서로 동일한 array 끼리 연산이 진행된다. 
# 이때 같은 위치에 있는 요소들 끼리 연산이 진행된다.
# 브로드캐스트 기능으로 서로 크기가 다른 array가 연산이 가능하기도 하다.

arr1 = np.array([[1,2,3], [4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr1.shape

(2, 3)

In [49]:
arr2 = np.array([[10, 11, 12], [13, 14, 15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

In [50]:
arr2.shape

(2, 3)

In [51]:
# array 덧셈

arr1+ arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [53]:
# array 뺄셈
arr1 -arr2

array([[-9, -9, -9],
       [-9, -9, -9]])

In [55]:
# array 곱셈
# array 곱셈은 행렬의 곱처럼 진행되는 것이 아니라 각 요소별로 곱셈이 진행됨

arr1*arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [57]:
# array 나눗셈

arr1 / arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [61]:
# numpy에서는 브로드캐스트라는 기능을 제공하여 서로 크기가 다른 array가 연산이 가능하다

arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr1.shape

(2, 3)

In [64]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [65]:
arr3.shape

(3,)

In [67]:
arr1 + arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [69]:
arr1*arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [70]:
arr1*10

array([[10, 20, 30],
       [40, 50, 60]])

In [72]:
arr1**2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [74]:
# array 인덱싱
# numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.
# 이때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작하는 것에 주의할것

arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr1[0]

0

In [78]:
arr1[3]

3

In [80]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

In [82]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])